# Site
repository: shaonianruntu/shaonianruntu.github.io
# favicon: images/favicon.ico

# Personal info
name: Nan Fang 方楠
title: Master's degree of Computer Science in reading
email: 514574496@qq.com
website: shaonianruntu.github.io
# Social links
# douban_username: test
# twitter_username: facespics
# github_username:  shaonianruntu
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
# linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb

# About Section
# about_title: About Me
about_profile_image: images/user.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Nan Fang 方楠. I am from Shanghai, China. I'm a first-year postgraduate student at the School of Computer Science, Hangzhou Dianzi University. And I am a person who has a strong desire for knowledge. I like to explore new things and have a team spirit. As well as machine learning and computer vision I also have experience making software and web apps. I have worked at a number of labs gaining teamwork and leadership skills.

  I am skilled in: <mark>Python</mark> <mark>Pytorch</mark> <mark>React</mark> <mark>Laravel</mark> <mark>C++</mark> and <mark>MySQL</mark>.

  And I am proficient in using: <mark>VSCode</mark> <mark>XCode</mark> <mark>Office</mark> <mark>macOS</mark> <mark>Ubuntu</mark> and <mark>Windows</mark>. 

  At the same time, I also have language skills of: <mark>CET-6</mark> <mark>CET-4</mark>.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in machine learing and software engineering some of my other interests and hobbies are:
   - Classical literture
   - Pop music
   - Table Tennis
   - Tourism 

  Here is the link to some of my friends' homepages, maybe you will be interested:
    - [高飞老师](https://fei-hdu.github.io/)
    - [罗宇矗同学](https://www.luoyuchu.com/)
    - [叶家豪同学](https://yjhmelody.github.io/)
    - [曹骁威学弟](https://accepteddoge.com/)
    - [柳婼学姐](https://www.liuchuo.net/)
    - [Kevin Tan 学长](https://kntan.coding.me/kntan/)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
